sudo: required
language: go

services:
  - docker

go:
  - "1.10.x"

branches:
  only:
    - master

script:
  - make test compile docker-build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
