[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  revision = "5e8e36f10a8c52315dcbb311319d78acb9c3bf83"

[[constraint]]
  name = "github.com/namsral/flag"
  version = "1.7.4-pre"

[prune]
  go-tests = true
  unused-packages = true
